remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Gonzalo Domínguez
description: Hello, welcome to my portfolio. My name is Gonzalo and I am a Software Engineering student in the University of Seville. Currently, I am in an exchange program in the University of Toulouse Capitole 1, followin the courses of the Master MIAGE Informations Systems.
